#ifndef CLIENT_COLUMN_ENUM_H
#define CLIENT_COLUMN_ENUM_H

enum ClientColumns
{
    NUMBERINHOUSEHOLD = 15,
    NUMBERCHILDRENINHOUSEHOLD = 16,
    ATTORNEY = 17,
    ATTORNEYPHONE = 18,
    ATTORNEYEMAIL = 19,
    ASSISTANTNAME = 20,
    ASSISTANTPHONE = 21,
    ASSISTANTEMAIL = 22
};

#endif // CLIENT_COLUMN_ENUM_H

