#ifndef PROCESS_COLUMN_ENUM_H
#define PROCESS_COLUMN_ENUM_H

enum ProcessColumns
{
    PROCESS_ID = 0,
    DISPUTETYPE = 1,
    CREATIONDATE = 2,
    UPDATEDDATE = 3,
    PROCESS_CREATIONDATETIME = 4,
    PROCESS_UPDATEDDATETIME = 5,
    DISPUTESTATE = 6,
    DISPUTEINTERNALSTATE = 7,
    DISPUTECOUNTY = 8,
    REFERALSOURCE = 9,
    INQUIRYTYPE = 10,
    INFOONLY = 11,
    ISCOURTCASE = 12,
    COURTDATE = 13,
    COURTCASETYPE = 14,
    COURTORDERTYPE = 15,
    TRANSLATORREQUIRED = 16,
    SESSIONTYPE = 17,
    MEDIATIONCLAUSE = 18,
    INDIRECTCHILDREN = 19,
    DIRECTCHILDREN = 20,
    INDIRECTADULT = 21,
    DIRECTADULT = 22,
    PROCESS_TAGS = 23
};

#endif // PROCESS_COLUMN_ENUM_H

