#ifndef SESSION_COLUMN_ENUM_H
#define SESSION_COLUMN_ENUM_H

enum SessionColumns
{
    ID = 0,
    FOREIGN_PROCESS_ID = 1,
    SESSIONSTATUS = 2,
    SESSIONOUTCOME = 3,
    SESSION_CREATEDDATETIME = 4,
    SESSION_UPDATEDDATETIME = 5,
    SCHEDULEDTIME = 6,
    MEDIATOR1 = 7,
    MEDIATOR2 = 8,
    OBSERVER1 = 9,
    OBSERVER2 = 10,
    SHUTTLE = 11
};

#endif // SESSION_COLUMN_ENUM_H

